name: Trivy Docker Scan

on:
  push:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Trivy
      run: |
        sudo apt update && sudo apt install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

    - name: Baixar imagem do Juice Shop
      run: docker pull bkimminich/juice-shop

    - name: Rodar Trivy na imagem Docker
      run: |
        mkdir -p relatorios
        trivy image bkimminich/juice-shop > relatorios/trivy-result.txt || echo "Trivy falhou"

    - name: Verificar resultado
      run: cat relatorios/trivy-result.txt
