name: Trivy Docker Scan

on:
  push:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Rodar Trivy via Docker
      run: |
        mkdir -p relatorios
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image bkimminich/juice-shop > relatorios/trivy-result.txt || echo "Trivy falhou"

    - name: Verificar resultado
      run: cat relatorios/trivy-result.txt
